export const mySkills = [
    "Teamwork",
    "Communication skills",
    "JavaScript: ES6+",
    "React",
    "React Router",
    "Redux (Toolkit)",
    "Redux-Saga",
    "React Hooks",
    "Redux Hooks",
    "Working with API (axios, fetch)",
    "Promises, Async/Await",
    "Local Storage",
    "Custom Hooks",
    "Styled Components",
    "Error handling",
    "HTML",
    "Responsive Web Design",
    "CSS BEM convenction",
    "CSS Grid",
    "CSS Flex",
    "Media Queries",
    "README",
    "Immutability",
    "Git",
    "NPM",
    "GitHub Pull Requests & Review",
    "Trello",
    "Scrum",
    "C++ (Object-oriented programming)",
    "C",
    "Python",
];

export const toLearn = [
    "TypeScript",
    "Node.js",
    "Java",
];